discord:
  webhook_url: ''
  command_channel_id: '1502947222981967904'
defaults:
  check_interval_seconds: 300
  jitter_seconds: 60
  request_timeout_seconds: 20
products:
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-10566-pokemon-mini-tin-box-fix8-karmesin-and-purpur-prismatische-entwicklungen-sammelkarten-2972603.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-10566-pokemon-mini-tin-box-fix8-karmesin-and-purpur-prismatische-entwicklungen-sammelkarten-2972603.html
  out_of_stock_text: &id001
  - Ausverkauft
  - Nicht verfügbar
  - Vergriffen
  - Derzeit nicht verfügbar
  - Sold out
  - Out of stock
  in_stock_text: &id002
  - In den Warenkorb
  - In den Einkaufswagen
  - Auf Lager
  - Lieferbar
  - Sofort lieferbar
  - Add to cart
  use_browser: true
- name: https://www.saturn.de/de/product/_pokemon-14234-pkm-kp105-mini-tin-de-sammelkartenspiel-2992657.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_pokemon-14234-pkm-kp105-mini-tin-de-sammelkartenspiel-2992657.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-45865-pokemon-ex-kampfdeck-juli-sammelkarten-2933604.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-45865-pokemon-ex-kampfdeck-juli-sammelkarten-2933604.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-10511-pokemon-kp085-binder-collection-mbe3-sammelkarten-2966410.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-10511-pokemon-kp085-binder-collection-mbe3-sammelkarten-2966410.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-10532-pokemon-kp085-top-trainer-box-mbe4-sammelkarten-2965784.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-10532-pokemon-kp085-top-trainer-box-mbe4-sammelkarten-2965784.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-10544-pokemon-kp085-poster-collection-mbe6-sammelkarten-2965785.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-10544-pokemon-kp085-poster-collection-mbe6-sammelkarten-2965785.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_pokemon-10603-pkm-kp085-accessory-pouch-collecti-sammelkarten-set-2980565.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_pokemon-10603-pkm-kp085-accessory-pouch-collecti-sammelkarten-set-2980565.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-pokemon-spezial-kollektion-sammelkarten-2977301.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-pokemon-spezial-kollektion-sammelkarten-2977301.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-20305-pkm-v-box-de-sortiert-2459607.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-20305-pkm-v-box-de-sortiert-2459607.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-45557-pokemon-kp035-poster-box-sammelkarten-2885372.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-45557-pokemon-kp035-poster-box-sammelkarten-2885372.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-pokemon-ex-premium-kollektion-sammelkarten-2977298.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-pokemon-ex-premium-kollektion-sammelkarten-2977298.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_pokemon-41092-cynthias-knakrack-ex-premium-k-mbe3-sammelkarten-2988491.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_pokemon-41092-cynthias-knakrack-ex-premium-k-mbe3-sammelkarten-2988491.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-pkm-kp065-top-trainer-box-de-sammelkartenspiel-2936729.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-pkm-kp065-top-trainer-box-de-sammelkartenspiel-2936729.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-41079-pokemon-kp09-top-trainer-box-sammelkarten-2974734.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-41079-pokemon-kp09-top-trainer-box-sammelkarten-2974734.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-45569-pokemon-kp01-booster-de-spielset-2857592.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-45569-pokemon-kp01-booster-de-spielset-2857592.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-45935-pkm-kp07-stellarkrone-booster-sammelkarten-2951644.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-45935-pkm-kp07-stellarkrone-booster-sammelkarten-2951644.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_pokemon-12918-me01-mega-entwicklung-top-trainer-box-guardevoir-sammelkartenspiel-3003328.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_pokemon-12918-me01-mega-entwicklung-top-trainer-box-guardevoir-sammelkartenspiel-3003328.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_pokemon-11077-kp10-ewige-rivalen-booster-fix36-sammelkarten-2988490.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_pokemon-11077-kp10-ewige-rivalen-booster-fix36-sammelkarten-2988490.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-20312-pokemon-top-trainer-box-sammelkarten-2911894.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-20312-pokemon-top-trainer-box-sammelkarten-2911894.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-10684-pokemon-weltmeisterschaftsdeck-2024-sammelkarten-2973281.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-10684-pokemon-weltmeisterschaftsdeck-2024-sammelkarten-2973281.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: https://www.saturn.de/de/product/_the-pokemon-company-int-45431-pokemon-swsh12-booster-de-sammelkarten-2834334.html
  shop: Saturn
  url: https://www.saturn.de/de/product/_the-pokemon-company-int-45431-pokemon-swsh12-booster-de-sammelkarten-2834334.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: Year of the Horse
  shop: swatch.com
  url: https://www.swatch.com/de-de/riding-the-clouds-suoz369/SUOZ369.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: UP IN SMOKE
  shop: swatch.com
  url: https://www.swatch.com/de-de/up-in-smoke-sb03z103/SB03Z103.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: Swatch Encyclopedia
  shop: swatch.com
  url: https://www.swatch.com/de-de/swatch-encyclopedia-s399000001/S399000001.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    SEA WASP

    155,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/sea-wasp-sscu09n100/SSCU09N100.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    PACIFIC SEA NETTLE

    155,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/pacific-sea-nettle-sscu09o100/SSCU09O100.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    MEDUSAE

    155,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/medusae-sscu09l100/SSCU09L100.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    FLOWER HAT

    155,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/flower-hat-sscu09p100/SSCU09P100.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'SWATCH PAY

    MEDUSAE PAY

    165,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/medusae-pay-sscu09l101-6000/SSCU09L101-6000.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'SWATCH PAY

    SEA WASP PAY

    165,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/sea-wasp-pay-sscu09n101-6000/SSCU09N101-6000.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    PARADISE BLOOM

    120,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/paradise-bloom-ss08b106/SS08B106.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    PARADISE PETALS

    120,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/paradise-petals-ss08p113/SS08P113.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    PARADISE MIST

    120,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/paradise-mist-ss08g111/SS08G111.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    PARADISE CANOPY

    120,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/paradise-canopy-ss08g112/SS08G112.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    THE CHARM OF MOM

    135,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/the-charm-of-mom-ysz101g/YSZ101G.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    MOTHER LIKE NO OTHER

    150,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/mother-like-no-other-ss08z106g/SS08Z106G.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    POLLOCK''S ALCHEMY

    110,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/pollock-s-alchemy-suoz366/SUOZ366.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    DEGAS''S DANCERS

    100,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/degas-s-dancers-so28z131/SO28Z131.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    KLEE''S BAVARIAN DON GIOVANNI

    100,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/klee-s-bavarian-don-giovanni-so28z703/SO28Z703.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    MONET''S PALAZZO DUCALE

    110,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/monet-s-palazzo-ducale-so29z150/SO29Z150.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'SWATCH PAY

    MONET''S PALAZZO DUCALE PAY!

    120,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/monet-s-palazzo-ducale-pay-so29z153-6000/SO29Z153-6000.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    IRIDESCENTLY PEACH

    185,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/iridescently-peach-syxs166/SYXS166.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    IRIDESCENTLY BLUE

    185,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/iridescently-blue-syxs164/SYXS164.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    BLUE REFLECTIVE

    205,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/blue-reflective-yvs539/YVS539.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    BERRY REFLECTIVE

    205,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/berry-reflective-yvs538/YVS538.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    SKY REFLECTIVE

    205,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/sky-reflective-yvs541/YVS541.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    PONDERING PATTERNS

    205,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/pondering-patterns-ss07s155/SS07S155.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
- name: 'NEU

    SHIMMERING WATERS

    220,00 €

    Inkl. MwSt.'
  shop: swatch.com
  url: https://www.swatch.com/de-de/shimmering-waters-ss07s157m/SS07S157M.html
  out_of_stock_text: *id001
  in_stock_text: *id002
  use_browser: true
categories:
- name: Pokemon Tin-Boxen @ Saturn
  shop: Saturn
  url: https://www.saturn.de/de/brand/pokemon-sammelkartenspiel/tin-boxen
  link_pattern: /de/product/
  use_browser: true
- name: Pokemon Kollektionen @ Saturn
  shop: Saturn
  url: https://www.saturn.de/de/promo-list/ent_brand_loa_pokemon_grid_kollektionen
  link_pattern: /de/product/
  use_browser: true
- name: Pokemon Premium Kollektionen @ Saturn
  shop: Saturn
  url: https://www.saturn.de/de/promo-list/ent_brand_loa_pokemon_grid_premium_kollektionen
  link_pattern: /de/product/
  use_browser: true
- name: Pokemon Top Trainer Boxen @ Saturn
  shop: Saturn
  url: https://www.saturn.de/de/brand/pokemon-sammelkartenspiel/top-trainer-boxen
  link_pattern: /de/product/
  use_browser: true
- name: Pokemon TCG Suche @ Saturn
  shop: Saturn
  url: https://www.saturn.de/de/promo-list/ent_brand_dpl_pokemon_tcg_sat?query=ent_brand_dpl_pokemon_tcg_sat&brand=POKEMON&marketplace=SATURN&page=2
  link_pattern: /de/product/
  use_browser: true
- name: 포켓몬
  shop: brand.naver.com
  url: https://brand.naver.com/pokemon/category/7d4ef8ffe7ca4427b42a1a61751656e4
  use_browser: true
  link_pattern: /pokemon/products/
- name: Royal Pop
  shop: swatch.com
  url: https://www.swatch.com/de-de/watches/new-watch-releases/
  link_pattern: /[A-Z][A-Z0-9_-]+\.html$
  use_browser: true
